
- name: Install Fail2Ban
  apt:
    name: fail2ban
    state: present
  tags: fail2ban

- name: Create configuration folder
  file:
    path: /etc/fail2ban
    state: directory
    owner: root
    group: root
    mode: '0755'
  tags: fail2ban

- name: Deploy configuration jail.local
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: '0644'
  notify: restart fail2ban
  tags: fail2ban

- name: Check Fail2Ban boot on startup
  systemd:
    name: fail2ban
    enabled: yes
    state: started
  tags: fail2ban

- name: Wait Fail2Ban to be started
  wait_for:
    timeout: 5
  tags: fail2ban

- name: Get Fail2Ban status
  command: fail2ban-client status
  register: fail2ban_status
  changed_when: false
  ignore_errors: yes
  tags: fail2ban

- name: Print Fail2Ban status
  debug:
    var: fail2ban_status.stdout_lines
  when: fail2ban_status is defined
  tags: fail2ban

- name: Get SSH jail status
  command: fail2ban-client status sshd
  register: fail2ban_ssh_status
  changed_when: false
  ignore_errors: yes
  tags: fail2ban

- name: Print SSH jail status
  debug:
    var: fail2ban_ssh_status.stdout_lines
  when: fail2ban_ssh_status is defined
  tags: fail2ban
