---
- name: Configure sysctl
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
    sysctl_file: /etc/sysctl.d/99-security.conf
  loop: "{{ sysctl_config | dict2items }}"
  tags: security

- name: Configure resource limits
  pam_limits:
    domain: "{{ item.domain }}"
    limit_type: "{{ item.type }}"
    limit_item: "{{ item.item }}"
    value: "{{ item.value }}"
  loop: "{{ limits_config }}"
  tags: security

- name: Activate AppArmor
  systemd:
    name: apparmor
    enabled: yes
    state: started
  tags: security

- name: Configure auto updates
  block:
    - name: Install unattended-upgrades
      apt:
        name: unattended-upgrades
        state: present
    
    - name: Configure unattended-upgrades
      template:
        src: 50unattended-upgrades.j2
        dest: /etc/apt/apt.conf.d/50unattended-upgrades
        owner: root
        group: root
        mode: '0644'
    
    - name: Active auto updates
      copy:
        content: |
          APT::Periodic::Update-Package-Lists "1";
          APT::Periodic::Download-Upgradeable-Packages "1";
          APT::Periodic::AutocleanInterval "7";
          APT::Periodic::Unattended-Upgrade "1";
        dest: /etc/apt/apt.conf.d/20auto-upgrades
        owner: root
        group: root
        mode: '0644'
  when: unattended_upgrades_enabled
  tags: security

- name: Configure PAM to limit login attempts
  lineinfile:
    path: /etc/pam.d/common-auth
    line: "auth required pam_tally2.so deny=5 unlock_time=900 onerr=fail"
    insertafter: EOF
    state: present
  tags: security

- name: Secure /tmp avec noexec
  mount:
    path: /tmp
    src: tmpfs
    fstype: tmpfs
    opts: defaults,noexec,nosuid,nodev,mode=1777
    state: mounted
  tags: security

- name: Disable core dumps
  pam_limits:
    domain: '*'
    limit_type: hard
    limit_item: core
    value: '0'
  tags: security

- name: Configure sensitives file permissions
  file:
    path: "{{ item }}"
    mode: '0600'
  loop:
    - /etc/ssh/sshd_config
    - /etc/shadow
    - /etc/gshadow
  tags: security
